name: ElementManager
version: 0.0.1
main: io.github.mkaksoy.elementmanager.Main
description: A lightweight plugin that simplifies server management in Minecraft
author: Mehmet Kaan AKSOY
api-version: '1.21.3'